# Group <%= resourcePlural %>

<%= resourceDescription %>

---

## <%= resourcePlural %> Collection [<%= route %>]

### Get all <%= resourcePlural %> [GET]

  + Response 200 (application/json)
    + Attributes (array[<%= resourceName %>Returned])

### Create a new <%= resourceName %> [POST]

  + Request (application/json)
    + Attributes (<%= resourceName %>Submitted)

  + Response 200 (application/json)
    + Attributes (<%= resourceName %>Returned)

## Single <%= resourceName %> [<%= route %>/{<%= resourceName.toLowerCase() %>_id}]

  + Parameters
    + <%= resourceName.toLowerCase() %>_id (<%= idType %>) - The unique ID of the <%= resourceName %> requested

### Get a <%= resourceName %> [GET]

  + Response 200 (application/json)
    + Attributes (<%= resourceName %>Returned)

### Update a <%= resourceName %> [PUT]
  
  + Request (application/json)
    + Attributes (<%= resourceName %>Submitted)

  + Response 200 (application/json)
    + Attributes (<%= resourceName %>Returned)

### Delete a <%= resourceName %> [DELETE]

  + Response 204 (application/json)
