### Error (object)

+ code: `ERROR`
+ message: `An error occurred`


### ErrorNotFound (Error)

+ code: `NOT_FOUND`
+ message: `The requested resource could not be found`

### ErrorUnauthorized (Error)

+ code: `UNAUTHORIZED`
+ message: `Access denied`

### ErrorForbidden (Error)

+ code: `FORBIDDEN`
+ message: `You are not permitted to perform that operation`

### ErrorBadRequest (Error) 

+ code: `BAD_REQUEST`
+ message: `There was a problem with the submitted data. Please correct the issue and try again`
+ errors (object) 
